### ISSUE TITLE
v0.0.1 Feedback

### ISSUE THREAD

**Issue by spannerisms** [fatmanspanda/SpriteAnimator#1]
Hi yes please

**Comment by Jighart** [comment]
Looking good so far! Couple of feature ideas:

- Zoom levels
- Ability to load multiple sprites next to one another for comparison
- Ability to change background color/game tileset (low prio)
- UI: one dropdown menu for the pose with extra buttons for the direction when applicable to reduce the list's size

Also for a long term usage: some sort of sprite library for easy access?

**Comment by Jighart** [comment]
Another feature suggestion: palette selector, so we can quickly swap to another mail or bunny palette.

**Comment by roxas232** [comment]
It would be sweet if it had a reload sprite button, and if it kept your current selections on reload
If no one else cares, I could potentially take a look at some point too

**Comment by roxas232** [comment]
It would also be sweet if you could see which sprite(s) a given frame corresponds to. Something like:

Head: A2
Body: B4
